In [6]:
import torch

torch.tensor(data, dtype=None, device=None, requires_grad=False)

data: 텐서로 변환하고자 하는 데이터입니다. 파이썬 리스트나 넘파이 배열 등이 사용될 수 있습니다.
dtype (optional): 텐서의 데이터 타입을 지정합니다. 기본값은 None으로, 자동으로 데이터 타입을 인식합니다.
device (optional): 텐서가 사용될 디바이스를 지정합니다. 기본값은 None으로, CPU 상에서 계산됩니다.
requires_grad (optional): 해당 텐서가 그래디언트를 계산할지 여부를 지정합니다. 기본값은 False입니다.

In [ ]:
import torch
data = [[1, 2, 3], [4, 5, 6]]
x = torch.tensor(data, dtype=torch.float32)
print(x)

tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [10]:
import torch

# 1차원 텐서 생성
x = torch.tensor([1, 2, 3])
print(x)

# 2차원 텐서 생성
y = torch.tensor([[1, 2, 3], [4, 5, 6]])
print(y)

# 모든 원소가 0인 3차원 텐서 생성
z = torch.zeros((2, 3, 4))
print(z)

# 모든 원소가 1인 4차원 텐서 생성
w = torch.ones((2, 2, 2, 2))
print(w)

# 랜덤한 값으로 채워진 3x3 텐서 생성
r = torch.rand((3, 3))
print(r)

tensor([1, 2, 3])
tensor([[1, 2, 3],
        [4, 5, 6]])
tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])
tensor([[[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]],


        [[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]]])
tensor([[0.1289, 0.2672, 0.1021],
        [0.7048, 0.9769, 0.8086],
        [0.0736, 0.6541, 0.1565]])


In [ ]:
#.Tensor나 .empty 함수는 메모리 상에 할당된 임의의 값으로 초기화된 텐서를 생성합니다.
# .Tensor 예제1
a = torch.Tensor([1, 2, 3])
print(a)

# .empty 예제
b = torch.empty(2, 3)
print(b)

# .Tensor 예제2
c = torch.Tensor(2,3)
print(c)

In [11]:
import torch

# 평균을 2, 표준편차를 1.5로 바꾸고 싶은 경우
mean = 2.0
std = 1.5
size = (3, 4)  # 원하는 사이즈 지정

# 평균이 2이고 표준 편차가 1.5인 정규 분포에서 무작위로 샘플 생성
samples = torch.randn(size) * std + mean

print(samples)

tensor([[1.5713, 1.6862, 2.0619, 2.5030],
        [6.9201, 1.1569, 1.9119, 3.6774],
        [0.4631, 1.7545, 1.1919, 0.0177]])


In [12]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(device)

cuda


In [14]:
import torch

# 데이터 타입
x = torch.tensor([1, 2, 3])
print(x.dtype)  #torch.int64
#기본값: torch.int64(int의 경우), torch.float32(float의 경우)

# 디바이스
device = torch.device('cpu')
x = torch.tensor([1, 2, 3], device=device)
print(x.device)  # cpu

# 크기
x = torch.tensor([1, 2, 3])
print(x.numel())  # 3

# 모양
x = torch.tensor([[1, 2], [3, 4], [5, 6]])
print(x.shape, x.size())  # torch.Size([3, 2]) torch.Size([3, 2])

# 모양 변경
x = torch.Tensor([1, 2, 3, 4])
print(x.size())
y = x.view(2, 2) #x.reshape(2,2)
print(y.size()) #torch.Size([2, 2])

torch.int64
cpu
3
torch.Size([3, 2]) torch.Size([3, 2])
torch.Size([4])
torch.Size([2, 2])


In [15]:
import torch

# 텐서 생성
a = torch.tensor([[1, 2], [3, 4]])
b = torch.tensor([[5, 6], [7, 8]])

# 덧셈
c = a + b
print(c)

# 뺄셈
d = a - b
print(d)

# 곱셈
e = a * b
print(e)

# 나눗셈
f = a / b
print(f)

# 행렬곱
g = torch.mm(a, b)
print(g)

# 점곱
h = torch.dot(torch.tensor([1, 2]), torch.tensor([3, 4]))
print(h)

tensor([[ 6,  8],
        [10, 12]])
tensor([[-4, -4],
        [-4, -4]])
tensor([[ 5, 12],
        [21, 32]])
tensor([[0.2000, 0.3333],
        [0.4286, 0.5000]])
tensor([[19, 22],
        [43, 50]])
tensor(11)


In [16]:
# 요소별 최대값 계산
i = torch.tensor([[1, 2], [3, 4]])
j = torch.tensor([[4, 3], [2, 1]])
k = torch.max(i, j)
print(k)

# 차원 축소
l = torch.tensor([[1, 2], [3, 4]])
m = torch.sum(l, dim=0)
print(m)

# 전치
n = torch.tensor([[1, 2], [3, 4]])
o = torch.transpose(n, 0, 1)
print(o)

tensor([[4, 3],
        [3, 4]])
tensor([4, 6])
tensor([[1, 3],
        [2, 4]])


In [17]:
# 인덱싱
p = torch.tensor([[1, 2], [3, 4], [5, 6]])
q = p[1, 0]
print(q)

# 슬라이싱
r = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
s = r[:, :2]
print(s)

# 조건부 인덱싱
t = torch.tensor([1, 2, 3, 4, 5])
u = t[t > 3]
print(u)

tensor(3)
tensor([[1, 2],
        [4, 5],
        [7, 8]])
tensor([4, 5])


In [1]:
import torch

# 텐서 생성
x = torch.tensor([1, 2, 3, 4])

# 텐서 차원 변경
y = x.unsqueeze(0)
print(y)

y = x.unsqueeze(1)
print(y)

y = x.squeeze()
print(y)

# 텐서 reshape
y = x.reshape(2, 2)
print(y)

# 텐서 정렬
x = torch.tensor([3, 2, 1])
y = torch.tensor([4, 5, 6])
z = torch.tensor([1, 2, 3])
a, b = torch.sort(x)
print(a, b)

a, b = torch.sort(y)
print(a, b)

a, b = torch.sort(z, descending=True)
print(a, b)

tensor([[1, 2, 3, 4]])
tensor([[1],
        [2],
        [3],
        [4]])
tensor([1, 2, 3, 4])
tensor([[1, 2],
        [3, 4]])
tensor([1, 2, 3]) tensor([2, 1, 0])
tensor([4, 5, 6]) tensor([0, 1, 2])
tensor([3, 2, 1]) tensor([2, 1, 0])


In [ ]:
import numpy as np

arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
print(np.concatenate((arr1, arr2), axis=1))
print(np.vstack((arr1, arr2)))
print(np.hstack((arr1, arr2)))


In [20]:
import numpy as np

arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
a1 = torch.tensor(arr1)
a2 = torch.tensor(arr2)
print(torch.cat((a1, a2), axis=1))
print(torch.vstack((a1, a2)))
print(torch.hstack((a1, a2)))

tensor([[1, 2, 5, 6],
        [3, 4, 7, 8]], dtype=torch.int32)
tensor([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]], dtype=torch.int32)
tensor([[1, 2, 5, 6],
        [3, 4, 7, 8]], dtype=torch.int32)


In [21]:
a = torch.tensor([1, 2, 3])
b = torch.tensor([1, 2, 3])
c = torch.tensor([1, 2, 4])

result1 = torch.eq(a, b)
result2 = torch.eq(a, c)

print(result1)  # Output: tensor([True, True, True])
print(result2)  # Output: tensor([True, True, False])

tensor([True, True, True])
tensor([ True,  True, False])


torch.softmax 소프트맥스 함수는 입력값을 확률(probability) 형태로 변환해주는 함수로, 다중 클래스 분류(Multi-class classification) 문제에서 예측된 점수를 확률로 변환하는 데 사용됩니다.

torch.softmax 함수의 사용 형식은 다음과 같습니다:

torch.softmax(input, dim=None, dtype=None)

input: 소프트맥스 함수를 적용하려는 입력 텐서(Tensor)
dim(선택적): 소프트맥스를 계산할 차원(Dimension). 기본값은 None이며, None인 경우 입력 텐서의 마지막 차원이 사용됩니다.
dtype(선택적): 출력 텐서의 데이터 타입(DataType). 기본값은 None이며, 입력 텐서의 데이터 타입과 동일한 데이터 타입으로 출력 텐서가 생성됩니다.

In [22]:
a = torch.tensor([1.0, 2.0, 3.0])  # 입력 텐서
softmax_output = torch.softmax(a, dim=0)  # dim=0으로 소프트맥스 계산
print(softmax_output)  # 출력: tensor([0.0900, 0.2447, 0.6652])

tensor([0.0900, 0.2447, 0.6652])


In [23]:
import torch

# 인플레이스 연산 예제
a = torch.tensor([1, 2, 3])
b = a
a.add_(torch.tensor([1, 1, 1]))
print(a)
print(b)

tensor([2, 3, 4])
tensor([2, 3, 4])


a.add_(torch.tensor([1, 1, 1]))는 a 텐서의 각 요소에 1씩 더하고, 그 결과를 다시 a에 저장합니다. 이때, add_ 메소드는 인플레이스 연산을 수행하므로, a 텐서의 값이 변경됩니다. 따라서, print(a)와 print(b)는 모두 [2, 3, 4]를 출력합니다. 이는 b가 a의 메모리 주소를 참조하므로, a의 값이 변경되면 b의 값도 함께 변경되기 때문입니다.

인플레이스 연산은 다음과 같이 _가 연산자 뒤에 붙는 메소드를 사용하여 수행할 수 있습니다.

add_
sub_
mul_
div_
pow_
sqrt_
round_
floor_
ceil_
clamp_
fill_
하지만, 인플레이스 연산은 주의해서 사용해야 합니다. 인플레이스 연산을 사용하면 원본 데이터가 변경되므로, 예상치 못한 결과를 초래할 수 있습니다. 따라서, 인플레이스 연산을 사용하기 전에는 반드시 복사본을 생성하여 원본 데이터를 보호해야 합니다.

In [24]:
import torch

# 3x3 크기의 텐서 생성
x = torch.zeros(3, 3)

# 모든 요소를 1로 채우기
x.fill_(1)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [26]:
import torch

# 3x3 크기의 텐서를 5로 채우기
x = torch.full((3, 3), 5)

print(x)

tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])
